name: webgl_helper
version: 0.3.0
author: Oliver Damm <oliver.damm@gmx.de>
description: A helper library for the WebGL API
homepage: https://github.com/blimster/webgl_helper

environment:
  sdk: '>=2.0.0-dev.69.0 <3.0.0'

dependencies:
  vector_math: "^2.0.8"

dev_dependencies:
  build_runner: ^0.9.2
  build_web_compilers: ^0.4.1